// defining all the action constants in one file


export const REQUEST_CAPSULES_DATA = 'REQUEST_CAPSULES_DATA';
export const REQUEST_CAPSULES_DATA_SUCCESS = 'REQUEST_CAPSULES_DATA_SUCCESS';
export const REQUEST_CAPSULES_DATA_FAILURE = 'REQUEST_CAPSULES_DATA_FAILURE';